In [1]:
import numpy as np
import random as rd
import queue 

### Esta funcion genera un estado aleatorio para el 8-Puzzle

In [20]:
class Nodo:
    board = []
    posEmpty = []
    
    parent = False
    def __init__(self,boardA,pos0,parent):
        self.board = boardA
        self.posEmpty = pos0
        self.parent = parent
        self.FindNeighbours()
        
    def FindNeighbours(self):
        self.neighbours = []
        nboard = []
        vals = [[0,-1],[0,1],[1,0],[-1,0]]
        for i in vals:
            nboard = self.board.copy()

            x = self.posEmpty[0] + i[0]
            y = self.posEmpty[1] + i[1]
            if x >=0 and y >=0 and x < 3 and y < 3:

                temp = self.board[x][y]
                nboard[x][y] = nboard[self.posEmpty[0]][self.posEmpty[1]]
                nboard[self.posEmpty[0]][self.posEmpty[1]] = temp
                self.neighbours.append([nboard,[x,y]])


In [3]:
def onState(state,actual):
    if len(state) >0:
        
        for node in state:
            if isObjetive(node,actual):
                return True
                break
        
    return False

In [4]:
def FindEmpty(board):
    for row in range(0,3):
        for col in range(0,3):
            if board[row,col] == 0:
                return [row,col]

In [5]:
def Crea_Estado_Aleatorio():
    lista = range(0,9)
    lista = rd.sample(lista,k=9)
    esIn = np.array([lista[0:3],lista[3:6],lista[6:10]])
    posEmpty = FindEmpty(esIn)
    esIn = Nodo(esIn,posEmpty,False)

    return esIn

In [6]:
def isObjetive(esAct,esObj):
    for row in range(0,3):
        for col in range(0,3):
            if esAct.board[row,col] != esObj[row,col]:
                return False
    return True

In [ ]:
estado = []
explored = []
esObj = np.array([[1,2,3],[4,5,6],[7,8,0]])
prueba = Nodo(esObj.copy(),[0,0],False)
esSt = Crea_Estado_Aleatorio()

q = queue.Queue()

estado.append(esSt)

q.put(esSt)

print esSt.board
node_obj = None

explored.append(node)
while not q.empty():
    actual = q.get()
    
    if isObjetive(actual,esObj):
        print "Yeii"
        node_obj = actual
        
        break
    
    for vec in actual.neighbours:
        if not onState(explored,vec[0]):
            node = Nodo(vec[0],vec[1],actual)
            q.put(node)
        else:
            print "Already"

            


[[1 6 8]
 [3 7 5]
 [0 2 4]]


In [40]:
q.empty()


True