In [227]:
import numpy as np

In [228]:
class n_queens:
    board = []
    n = None
    queens = None
    
    def __init__(self,n,board,queens = []):
        self.board = board
        self.n = n
        self.queens = queens
     
    def getDiagonals(self,pos):
        
        row,col = pos
        diag = []
        
        for i,j in zip(range(row,self.n),range(col,self.n)):
            if (i,j) != pos:
                diag.append((i,j))
        
        for i,j in zip(range(row,-1,-1),range(col,-1,-1)):
            if (i,j) != pos:
                diag.append((i,j))
                
        for i,j in zip(range(row,-1,-1),range(col,self.n)):
            if (i,j) != pos:
                diag.append((i,j))
       
        for i,j in zip(range(row,self.n),range(col,-1,-1)):
            if (i,j) != pos:
                diag.append((i,j))
        
        diag = sorted(diag,key = lambda x : x[0])
        return diag   
    
    def getRows(self,queen):
        rows = []
        row = queen[0]
        for i in range(self.n):
            rows.append((row,i))
        return rows

    def getColumns(self,queen):
        cols = []
        col = queen[1]
        for i in range(self.n):
            cols.append((i,col))
        
        return cols
    
    def isSafe(self,queen):

        
        for i in self.getRows(queen):
            if self.board[i] == 1 and i != queen:
                return False
        
        for i in self.getColumns(queen):
            if self.board[i] == 1 and i != queen:
                return False
        
        for i in self.getDiagonals(queen):
            if self.board[i] == 1 and i != queen:
                return False
        return True
    
    def isGoal(self):
        
        if len(self.queens) == self.n:
            for queen in self.queens:
                if not self.isSafe(queen):
                    print queen
                    return False
            return True

In [229]:
class BackTracking(n_queens):
    neighbours = None
    
    def __init__(self,n,board,queens = []):
        n_queens.__init__(self,n,board,queens)
        #return None
    
    def getNeighbours(self):
        self.neighbours = []
        for i in range(self.n):
            for j in range(self.n):
                if not (i,j) in self.queens:
                    self.neighbours.append((i,j))


In [241]:
def executeBack(node):
    
    if node.isGoal():
        return node
    
    node.getNeighbours()
    
    for new in node.neighbours:
        if node.isSafe(new):
            board = node.board.copy()
            queens = node.queens[:]
            
            board[new] = 1
            queens.append(new)
            newobj = BackTracking(node.n,board,queens)
            
            final_node = executeBack(newobj)
            
            if final_node:
                return final_node
    return False

        

n = 4   
back = BackTracking(n,np.zeros((n,n)))
p = executeBack(back)
if p:
    print p.board


[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [243]:
class MRV(BackTracking):
    remaining = None
    
    def __init__(self,n,board,queens = []):
        BackTracking.__init__(self,n,board,queens)

    
    def getRemainingValues(self,pos):
        board = self.board.copy()
        rows = self.getRows(pos)
        cols = self.getColumns(pos)
        diags = self.get
        
        for i in range(self.n):
            for j in range(self.n):
                print i,j
        
        return

p = MRV(n,np.zeros((n,n)))
p.getRemainingValues((0,0))

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3
3 0
3 1
3 2
3 3


In [232]:
def DEGREE(node):
    
    if node.isGoal():
        return node
    
    node.getNeighbours()
    node.neighbours = sorted(node.neighbours,key = lambda x: len(x.constrataints),reverse = True)
    
    for new in node.neighbours:

        final_node = BackTracking(new)
        
        if final_node:
            return final_node
    
    return False
    
n = 5
n_queen = Board(n,np.zeros((n,n)))
print DEGREE(n_queen).queens


TypeError: __init__() takes at least 3 arguments (2 given)

In [ ]:
def MRV(node):
    
    if node.isGoal():
        return node
    
    node.getNeighbours()
    node.neighbours = sorted(node.neighbours,key = lambda x: len(x.constrataints))
    
    for new in node.neighbours:

        final_node = BackTracking(new)
        
        if final_node:
            return final_node
    
    return False
n = 5
n_queen = Board(n,np.zeros((n,n)))
print MRV(n_queen).queens
