In [3]:
import numpy as np

In [8]:
class Board:
    board = []    # Tablero
    n = None      # Cantidad de reinas
    parent = None # Apuntador al nodo padre
    queens = None   # Posicion de las reinas
    constrataints = None #Posiciones que no pueden usarse
    neighbours = None # Vecinos de este nodo
    
    def __init__(self,n,board,parent = None,queens = [], constrataints = []):
        
        self.n = n
        self.board = board
        self.parent = parent
        self.queens = queens
        self.constrataints = constrataints
    
    def getConstrataints(self,pos,constrataints):
        # Esta funcion obtiene las posiciones que no pueden ser usadas
        (i,j) = pos 
        
        #Agrega todos los de la misma columna
        while i < self.n:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            i+=1
        
        (i,j) = pos
        while i >= 0:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            i-=1
        
        #Agrega las posiciones de la misma fila
        (i,j) = pos
        while j < self.n:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j+=1
        
        (i,j) = pos
        while j >= 0:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j-=1
            
        #Agrega las posiciones de la diagonal izquierda hacia arriba
        (i,j) = pos
        while j >= 0 and i >= 0:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j-=1
            i-=1
        
        #Agrega las posiciones de la diagonal izquierda hacia arriba
        (i,j) = pos
        while j >= 0 and i < n:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j-=1
            i+=1
            
        (i,j) = pos
        while j < n and i >= 0:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j+=1
            i-=1
            
        #Agrega las posiciones de la diagonal derecha hacia abajo
        (i,j) = pos
        while j < n and i <n:
            if not (i,j) in constrataints:
                constrataints.append((i,j))
            j+=1
            i+=1
        constrataints = sorted(constrataints,key= lambda x: x[0])

        return constrataints
    
    
    #Esta funcion obtiene los vecinos
    def getNeighbours(self):
        board = None
        self.neighbours = []

        for j in range(self.n):
            for i in range(self.n):
                if not (i,j) in self.constrataints:
                    
                    board = self.board.copy()
                    board[i,j] = 1

                    
                    queens = self.queens[:]
                    queens.append((i,j))
                    
                    constrataints = self.constrataints[:]
                    constrataints = self.getConstrataints((i,j),constrataints)
                    
                    self.neighbours.append(Board(n,board,self,queens,constrataints))
                    
    def isGoal(self):
        return True if len(self.queens) == self.n else False

In [7]:
def BackTracking(node):
    if node.isGoal():
        return node
    
    node.getNeighbours()
    
    for new in node.neighbours:
        final_node = BackTracking(new)
        
        if final_node:
            return final_node
    
    return False
    
n = 4
n_queen = Board(n,np.zeros((n,n)))
node= BackTracking(n_queen)

if node:
    print node.queens
    print node.board




[(1, 0), (3, 1), (0, 2), (2, 3)]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
