In [1]:
import numpy as np
import collections 
import random as rd


In [15]:
class puzzle:
    NORTH ,EAST ,SOUTH ,WEST = 1,2,3,4
    board = None
    parent = None
    depth = None
    neighbours = None
    
    def __init__(self,board,parent=None,depth=0):
        self.board = board
        self.parent = parent
        self.depth = depth
    
    def getMoves(self):
        
        return
    
    def moveBoard(self,move):
        board = self.board.copy()
        
        if move == self.NORTH:
            for i in reversed(range(3)):
                for j in reversed(range(3)):
                    
                    print i,j
        
        
        
        
        
    

In [16]:
def CreaEstado():
    board = np.zeros((4,4))
    randpos = (rd.randint(0,3),rd.randint(0,3))
    board[randpos] = 2
    
    return puzzle(board)
    
startObj = CreaEstado()
print startObj.board
print startObj.moveBoard(1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 0. 0.]]
2 2
2 1
2 0
1 2
1 1
1 0
0 2
0 1
0 0
None
