In [2]:
import numpy as np
import collections 
import random as rd


In [104]:
class puzzle:
    NORTH ,SOUTH,EAST ,WEST = 1,2,3,4
    board = None
    parent = None
    depth = None
    neighbours = None
    isMax = False
    
    def __init__(self,board,parent=None,depth=0,isMax=True):
        self.board = board
        self.parent = parent
        if self.parent:
            self.depth = self.parent.depth + 1
        else:
            self.depth = depth
        self.isMax = isMax
        self.getNeighbours()
    
    def getMoves(self,move):

        moves = []
        
        
        if move == self.NORTH:
            direction = (-1,0)
            #Recorremos las fichas de arriba hacia abajo
            for i in range(1,4):
                for j in range(4):
                    moves.append([(i,j)])
        
        if move == self.SOUTH:
            direction = (1,0)
            #Recorremos las fichas de abajo hacia arriba
            for i in reversed(range(0,3)):
                for j in range(4):
                    moves.append([(i,j)])
            
        if move == self.EAST:
            direction = (0,1)
            #Recorremos las fichas de izquierda a derecha
            for j in reversed(range(0,4)):
                for i in range(4):
                    moves.append([(i,j)])
                    
        if move == self.WEST:
            direction = (0,-1)
             #Recorremos las fichas de derecha a izquierda
            for j in range(0,4):
                for i in range(4):
                    moves.append([(i,j)])
        
        
        return moves,direction
    
    #Funcion que realiza los merges de los numeros iguales
    def mergeNumbers(self,obj,dest,board):
        
        if board[obj] == board[dest]:
            board[dest] =board[obj] + board[dest]
            board[obj] = 0
            return True
        return False
            
    def movePiece(self,src,dest,board):
        if dest[0] < 0 or dest[1] < 0  or dest[1] > 3 or dest[0] > 3:
            return False
        elif board[dest] != 0:
            return self.mergeNumbers(src,dest,board)
        
        else:
            board[dest] = board[src]
            board[src] = 0
            return True
            
    
    #Funcion que realiza los movimientos de las fichas
    def moveBoard(self,move):
        board = self.board.copy()
        moves,direction = self.getMoves(move)
        
        for mv in moves:
            src = mv[0]

            dest = src
            band = True
            while band:
                dest = (dest[0] + direction[0],dest[1] + direction[1])
                band = self.movePiece(src,dest,board)
                src = dest

        return board
        
    def getNeighbours(self):
        self.neighbours = []
        if self.isMax:
            for i in range(1,5):
                board = self.moveBoard(i)
                #El siguiente if nos permite podar un poco mas los vecinos.
                if not np.array_equal(self.board,board):
                    self.neighbours.append(board)
        else:
            self.getMinNeighbours()
    
    def getMinNeighbours(self):
        for i in range(4):
            for j in range(4):
                if self.board[i,j] == 0:
                    board1 =  self.board.copy()
                    board2 = self.board.copy()
                    board1[i,j] = 2
                    board2[i,j] = 4
                    self.neighbours.append(board1)
                    self.neighbours.append(board2)
                    
                    
    
    def getScore(self):
        return np.sum(self.board)

    def isGoal(self):
        return np.any(self.board == 2048)
           
    

In [105]:
def CreaEstado():
    board = np.zeros((4,4))
    possvalues = [2,4]
    for i in range(2):
        randpos = (rd.randint(0,3),rd.randint(0,3))
        randvalue = rd.randint(0,1)
        if board[randpos] == 0:
            board[randpos] = possvalues[randvalue]
        else:
            i-=1
    
    return puzzle(board)

startObj = CreaEstado()
print startObj.board

print "\n"
for i in startObj.neighbours:
    print i

[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[4. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [4. 0. 0. 0.]]
[[0. 0. 0. 2.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [0. 0. 0. 0.]]


In [118]:
def alpha_beta(node,maxdepth,isMax,alpha,beta):
    print node.board
    
    if node.depth == maxdepth or node.isGoal():
        return node,
    
    if isMax:
        print "Max"
        
    else:
        print "Min"
        
        
        
alpha_beta(startObj,3,True,0,0)

[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 0.]]
Max
